manipulator:
  kinematics_solver: ur_kinematics/UR10KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 12
ensenso_n10:
  kinematics_solver: ur_kinematics/UR10KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 12
